# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.cache/wt [current_project]
set_property parent.project_path C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/ref_code/coe/9.Memory_Inst_Test/inst_rom.coe
add_files C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/ref_code/coe/7.J_Inst_Test/inst_rom.coe
add_files C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/ref_code/coe/10.M_Inst_Hazard_Test/inst_rom.coe
add_files C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/ref_code/coe/11.CP0_Inst_Test/inst_rom.coe
read_verilog C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/new/defines.vh
set_property is_global_include true [get_files C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/new/defines.vh]
read_verilog -library xil_defaultlib {
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/ALU.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/new/Data_Memory_Controller.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/HazardUnit.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/Register.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/ShiftLeft2.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/SignExtend.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/adder.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/controller.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/cp0_reg.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/datapath.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/div.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/eqcmp.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/new/flopenr.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/new/flopenrc.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/new/flopr.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/hilo_reg.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/mips.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/mux2.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/new/mux3.v
  C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/imports/rtl/top.v
}
read_ip -quiet C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet C:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/a/Desktop/MIPS32_SOC_lite/pipelineX.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_lite_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_lite_top_utilization_synth.rpt -pb soc_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
